### ISSUE TITLE
[Backend]: สร้าง API สำหรับยืนยันตัวตนของผู้ใช้งาน

### ISSUE THREAD

**Issue by ohmpzz** [GodKoZ/godkoz-money-book#17]
ให้สร้าง API ยืนยันตัวตนด้วย Gmail, Facebook และ Line ให้เก็บข้อมูลผู้ใช้ให้ตรงกับข้อมูลในฐานข้อมูลที่กำหนดกัน

- [x] สร้าง API ยืนยันตัวตนด้วย Gmail
- [x] สร้าง API ยืนยันตัวตนด้วย Facebook
- [x] สร้าง API ยืนยันตัวตนด้วย LINE

**Comment by ohmpzz** [comment]
เบ้นอยากทำอันไหน gmail, facebook หรือ LINE 

เดียวจะขึ้นโครงสร้างให้ก่อน

เก็บ token เป็นอะไรดี cookie เป็น jwt หรือ token id แบบเดิม?

**Comment by rojarat** [comment]
อยากทำ line แล้วก็คิดว่าใช้ jwt ก็น่าจะดีนะ

**Comment by ohmpzz** [comment]
แบบให้ gen jwt เก็บลง cookie แล้วให้ยืนยัน token กับฐานข้อมูลใช่มั้ย?  @rojarat

**Comment by ohmpzz** [comment]
@rojarat

**Comment by rojarat** [comment]
@ohmpzz

**Comment by rojarat** [comment]
@athikannn
